### ISSUE TITLE
 all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 0 dimension(s)

### ISSUE THREAD

**Issue by Tian14267** [nerox8664/pytorch2keras#115]
**Describe the bug**
**I get this error:**
Traceback (most recent call last):
  File "torch2keras.py", line 83, in <module>
    transforms_2()
  File "torch2keras.py", line 76, in transforms_2
    k_model = pytorch_to_keras(model.module, input_var, (3, 448, 448), verbose=True, name_policy='short')
  File "/home/fffan/.local/lib/python3.7/site-packages/pytorch2keras/converter.py", line 83, in pytorch_to_keras
    verbose=verbose, change_ordering=change_ordering)
  File "/home/fffan/.local/lib/python3.7/site-packages/onnx2keras/converter.py", line 181, in onnx_to_keras
    keras_names
  File "/home/fffan/.local/lib/python3.7/site-packages/onnx2keras/reshape_layers.py", line 107, in convert_concat
    layers[node_name] = np.concatenate(layer_input, axis=params['axis'])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 0 dimension(s)

**Code**
![9CD1FD67666CB11EC1E3C893B041C267](https://user-images.githubusercontent.com/27938135/86864109-25b47b80-c0ff-11ea-97fb-eb1cc17e93ee.jpg)

**Environment (please complete the following information):**
 - onnx: 1.7
 - Python  3.7
 - pyotrch2keras: 0.2.4

Does somebody know how solve this problem?

**Comment by SWHL** [comment]
I have the same problem with you.

**Comment by thbupt** [comment]
same problem too.

**Comment by thbupt** [comment]
same problem too.

**Comment by nikhilbyte** [comment]
did someone manage to solve it
?
