### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not list

### ISSUE THREAD

**Issue by zhang-f** [nerox8664/pytorch2keras#116]
The model transformation was successful, but this error occurred while loading
The keras version is 2.2.2
![image](https://user-images.githubusercontent.com/36390250/86882774-5b6b5b80-c123-11ea-829f-719e0fa357e4.png)

**Comment by zhang-f** [comment]
loading model
Traceback (most recent call last):
  File "gtsrb_visualize_example.py", line 232, in <module>
    main()
  File "gtsrb_visualize_example.py", line 224, in main
    gtsrb_visualize_label_scan_bottom_right_white_4()
  File "gtsrb_visualize_example.py", line 185, in gtsrb_visualize_label_scan_bottom_right_white_4
    model = load_model(model_file)
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/engine/saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/engine/saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/engine/network.py", line 1027, in from_config
    process_node(layer, node_data)
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/engine/network.py", line 986, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/fanzh/.conda/envs/nc/lib/python3.6/site-packages/keras/layers/normalization.py", line 92, in build
    dim = input_shape[self.axis]
TypeError: tuple indices must be integers or slices, not list

**Comment by nerox8664** [comment]
Hello @zhang-f .
Can you please provide the model you try to convert?

**Comment by zhang-f** [comment]
Sorry for my late reply! @nerox8664 Thank you very much for reading my question!
I've put two models and code on this cloud disk, thanks again! https://cloud.tsinghua.edu.cn/d/962383929f244fe79559/

**Comment by zhang-f** [comment]
I think I found this bug.This is because my version of TensorFlow is 1.10.0, but this library contains onnx2Keras, which requires version 2.0. Thanks for the enthusiastic reply from the  @nerox8664 !Thank you very much for this wonderful project, too.
