### ISSUE TITLE
Error on running test file to convert resnet50 to keras 

### ISSUE THREAD

**Issue by anshu1106** [nerox8664/pytorch2keras#16]
Getting this error:
KeyError: <tf.Tensor 'maxpool0.13212125626892746/transpose_1:0' shape=(?, 64, 56, 56) dtype=float32>

**Comment by klory** [comment]
Got the same error here

**Comment by nerox8664** [comment]
Hello there. I've figured that out for now, it was a small bug in convolution layer convertation, so I've tested ResNet50 and ResNet50 and all works normally for now.

**Comment by anshu1106** [comment]
Still getting the same error while trying to convert custom pytorch model to keras.

**Comment by nerox8664** [comment]
Hello @anshu1106.
I tested ResNet50 twice, all looks good. Can you tell me your Keras, Tensorflow and PyTorch versions?

Tested version:
* TF 1.7.0
* Keras 2.6.1
* PyTorch 0.4.0

**Comment by Ai-is-light** [comment]
@nerox8664 @anshu1106 
My environment is 
I got this error. I used the resnet50 as the backbone of the fpn.
ValueError: Shape must be rank 1 but is rank 4 for 'resnet.bn10.162173865941/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,64,192,192], [1,64,1,1], [1,64,1,1], [1,64,1,1], [1,64,1,1].
Looking forward any replies.
Thanks

**Comment by Ai-is-light** [comment]
After update tensorflow to the latest version, it works

**Comment by Ai-is-light** [comment]
@nerox8664 I got this bug again with TF1.7 and TF1.8 with keras 2.2.0, although l have succeed in converting the pytorch model to keras model and successfully test with the generated data. When I run the converted model to the real image, the error as following:
sing TensorFlow backend.
2018-06-28 16:46:07.220030: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-06-28 16:46:08.465952: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.62
pciBusID: 0000:88:00.0
totalMemory: 10.91GiB freeMemory: 10.55GiB
2018-06-28 16:46:08.466254: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-06-28 16:46:15.197435: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-06-28 16:46:15.197503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0
2018-06-28 16:46:15.197512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N
2018-06-28 16:46:15.230101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10191 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:88:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "generate_heatmap_kerastf_dress.py", line 342, in <module>
    main()
  File "generate_heatmap_kerastf_dress.py", line 288, in main
    keras_model = load_model('./dress_freeze_kerastf/fpn-resnet-weights-and-model.h5')
  File "/home/yuyongbo/object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/engine/saving.py", line 261, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/yuyongbo/object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/engine/saving.py", line 335, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/engine/network.py", line 1046, in from_config
    process_node(layer, node_data)
  File "object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/engine/network.py", line 1003, in process_node
    layer(input_tensors[0], **kwargs)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/engine/base_layer.py", line 460, in __call__
    output = self.call(inputs, **kwargs)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/layers/normalization.py", line 204, in call
    training=training)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/backend/tensorflow_backend.py", line 3069, in in_train_phase
    x = switch(training, x, alt)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/backend/tensorflow_backend.py", line 3004, in switch
    else_expression_fn)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2072, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1913, in BuildCondBranch
    original_result = fn()
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/layers/normalization.py", line 165, in normalize_inference
    epsilon=self.epsilon)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/Keras-2.2.0-py2.7.egg/keras/backend/tensorflow_backend.py", line 1894, in batch_normalization
    is_training=False
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py", line 904, in fused_batch_norm
    name=name)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 3429, in _fused_batch_norm
    is_training=is_training, name=name)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home//object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/object_detection/venv-torch-latest/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 4 for 'resnet.bn10.157254383317/cond/FusedBatchNorm' (op: 'FusedBatchNorm') with input shapes: [?,64,192,192], [1,64,1,1], [1,64,1,1], [1,64,1,1], [1,64,1,1].
