### ISSUE TITLE
Multiple Inputs

### ISSUE THREAD

**Issue by rchavezj** [nerox8664/pytorch2keras#20]
Since my forward function in PyTorch has three inputs, I was wondering if the pytorch2keras converter can handle multiple variables? Does the converter support tuple inputs?

For example:
x is a (48,15)
y is (48,)
z is a tuple of two of these --> (2, 48, 128)

from converter import pytorch_to_keras
---> we should specify shape of the input tensor
k_model = pytorch_to_keras(model, (x, y, z), (???), verbose=True)

**Comment by nerox8664** [comment]
Hello @rchavezj. 

>  Since my forward function in PyTorch has three inputs, I was wondering if the pytorch2keras converter can handle multiple variables? Does the converter support tuple inputs?

No, the converter doesn't support multiple input for now. I'll add it as soon as possible :)

**Comment by nerox8664** [comment]
@rchavezj you can check it now with latest master commit.

**Comment by rchavezj** [comment]
Thank you! And lastly, based on the three input dimensions I provided above, how should the third input argument for pytorch_to_keras look like?

**Comment by rchavezj** [comment]
Nevermind I saw your test version.

**Comment by rchavezj** [comment]
AlsoI get the following error from running multiple_inputs.py


 Traceback (most recent call last):
  File "multiple_inputs.py", line 5, in <module>
    from pytorch2keras.converter import pytorch_to_keras
ImportError: No module named pytorch2keras.converter

**Comment by nerox8664** [comment]
hello. If you share the model definition, i can debug this case for the converter.

**Comment by rchavezj** [comment]
Under eval/eval.py. You need to read readme first

https://github.com/taoxugit/AttnGAN

**Comment by rchavezj** [comment]
under line 86 and line 92 inside eval.py are models I wish to convert to keras if possible

**Comment by UdonDa** [comment]
Have you been able to convert to keras model using multiple inputs?
If you can, please tell me how.

**Comment by nerox8664** [comment]
@UdonDa hello. 
You can check it with `tests/layers/multiple_inputs.py` test in the repository.

**Comment by UdonDa** [comment]
@nerox8664 Thanks!
However, I encountered this error.
I concatenate the input image and condition in the channel direction and change it to [13, 256, 256] and then input it to the model.
```
Traceback (most recent call last):
  File "main.py", line 118, in <module>
    main(config)
  File "main.py", line 50, in main
    solver.train()
  File "~/hoge/solver_cpu.py", line 316, in train
    k_model = pytorch_to_keras(self.G, [x_real, c_trg], [(3, 256, 256,), (10, 256, 256,)], verbose=True)
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/pytorch2keras/converter.py", line 182, in pytorch_to_keras
    short_names
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/pytorch2keras/layers.py", line 185, in convert_conv
    layers[scope_name] = conv(layers[input_name])
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/keras/engine/base_layer.py", line 436, in __call__
    self.set_weights(self._initial_weights)
  File "~.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1057, in set_weights
    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (7, 7, 3, 64) not compatible with provided weight shape (7, 7, 13, 64)
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fbc619f6e48>>
Traceback (most recent call last):
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 349, in __del__
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 322, in _shutdown_workers
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/threading.py", line 521, in set
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/threading.py", line 364, in notify_all
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/threading.py", line 347, in notify
TypeError: 'NoneType' object is not callable
```
