### ISSUE TITLE
Error:about the new customized layer

### ISSUE THREAD

**Issue by Ai-is-light** [nerox8664/pytorch2keras#29]
@nerox8664 Hi, we train a model with customized, called SegmentConsensus, layer by torch.0.4.0, and getting the following error:
Using TensorFlow backend.
Freezing BatchNorm2D except the first one.
Freezing BatchNorm2D except the first one.
Traceback (most recent call last):
  File "pytorch_trn-res2keras-tf.py", line 27, in <module>
    keras_model = pytorch_to_keras(pytorch_model, input_var, (4, 3, 224, 224), verbose=True)
  File "/home/intellif/framework_exchange/pytorch2keras/pytorch2keras/converter.py", line 91, in pytorch_to_keras
    trace, torch_out = torch.jit.get_trace_graph(model, tuple(args))
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/intellif/framework_exchange/pytorch2keras/pytorch2keras/converter.py", line 29, in set_training
    yield
  File "/home/intellif/framework_exchange/pytorch2keras/pytorch2keras/converter.py", line 91, in pytorch_to_keras
    trace, torch_out = torch.jit.get_trace_graph(model, tuple(args))
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/jit/__init__.py", line 255, in get_trace_graph
    return LegacyTracedModule(f, nderivs=nderivs)(*args, **kwargs)
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/jit/__init__.py", line 288, in forward
    out = self.inner(*trace_inputs)
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/intellif/framework_exchange/pytorch2keras/models.py", line 338, in forward
    output = self.consensus(base_out)
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/intellif/anaconda2/envs/py3torch4/lib/python3.5/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/intellif/framework_exchange/pytorch2keras/ops/basic_ops.py", line 47, in forward
    return SegmentConsensus(self.consensus_type, self.dim)(input)
RuntimeError: Attempted to trace SegmentConsensus, but tracing of legacy functions is not supported

How to understand tracing of legacy functions is not supported

**Comment by nerox8664** [comment]
Hello @Ai-is-light.
This error occurs when PyTorch can't trace your model properly. The reason may be: custom operations, ffi, wrong arguments order and something like that. So, you've got the error related to pytorch's jit.

You can check, if the model works with your dummy-variables without any converters.
