### ISSUE TITLE
Error: InstanceNormalization after ConvTranspose2d

### ISSUE THREAD

**Issue by UdonDa** [nerox8664/pytorch2keras#37]
I want to apply InstanceNormalization after nn.ConvTranspose2d. However, an error appeared and it was impossible.
Can not it work with the current program?

Write down the test code and a error.

source code.
```
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
from pytorch2keras.converter import pytorch_to_keras
from sys import exit


class TestMultipleInputs(nn.Module):
    """Module for Conv2d conversion testing
    """

    def __init__(self, inp=10, out=16, kernel_size=3, bias=True):
        super(TestMultipleInputs, self).__init__()
        self.conv2d = nn.Conv2d(inp, out, kernel_size=kernel_size, bias=bias)
        self.deconv2d = nn.ConvTranspose2d(inp, out, kernel_size=kernel_size, bias=bias)
        self.in2d = nn.InstanceNorm2d(out)

    def forward(self, x, y, z):
        # return self.in2d(self.conv2d(x)) + self.in2d(self.conv2d(y)) + self.in2d(self.conv2d(z))
        return self.in2d(self.deconv2d(x)) + self.in2d(self.deconv2d(y)) + self.in2d(self.deconv2d(z))
        # return self.conv2d(x) + self.conv2d(y) + self.conv2d(z)


if __name__ == '__main__':
    max_error = 0

    kernel_size = np.random.randint(1, 7)
    inp = np.random.randint(kernel_size + 1, 100)
    out = np.random.randint(1, 100)

    model = TestMultipleInputs(inp, out, kernel_size, inp % 2)

    input_np = np.random.uniform(0, 1, (1, inp, inp, inp))
    input_var = Variable(torch.FloatTensor(input_np))
    input_var2 = Variable(torch.FloatTensor(input_np))
    input_var3 = Variable(torch.FloatTensor(input_np))

    print(input_var.size())
    print(input_var2.size())
    print(input_var3.size())

    output = model(input_var, input_var2, input_var3)

    k_model = pytorch_to_keras(model, [input_var, input_var2, input_var3], [(inp, inp, inp,), (inp, inp, inp,), (inp, inp, inp,)], verbose=True)

    
    pytorch_output = output.data.numpy()
    keras_output = k_model.predict([input_np, input_np, input_np])
```

an error.
```
Using TensorFlow backend.
torch.Size([1, 92, 92, 92])
torch.Size([1, 92, 92, 92])
torch.Size([1, 92, 92, 92])
graph(%0 : Float(1, 92, 92, 92)
      %1 : Float(1, 92, 92, 92)
      %2 : Float(1, 92, 92, 92)
      %3 : Float(53, 92, 1, 1)
      %4 : Float(92, 53, 1, 1)) {
  %5 : Float(1, 53, 92, 92) = onnx::ConvTranspose[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%0, %4), scope: TestMultipleInputs/ConvTranspose2d[deconv2d]
  %6 : Dynamic = onnx::Constant[value=<Tensor>](), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %7 : Dynamic = onnx::Constant[value=<Tensor>](), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %8 : Float(1, 53, 92, 92) = onnx::InstanceNormalization[epsilon=1e-05](%5, %6, %7), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %9 : Float(1, 53, 92, 92) = onnx::ConvTranspose[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%1, %4), scope: TestMultipleInputs/ConvTranspose2d[deconv2d]
  %10 : Dynamic = onnx::Constant[value=<Tensor>](), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %11 : Dynamic = onnx::Constant[value=<Tensor>](), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %12 : Float(1, 53, 92, 92) = onnx::InstanceNormalization[epsilon=1e-05](%9, %10, %11), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %13 : Float(1, 53, 92, 92) = onnx::Add(%8, %12), scope: TestMultipleInputs
  %14 : Float(1, 53, 92, 92) = onnx::ConvTranspose[dilations=[1, 1], group=1, kernel_shape=[1, 1], pads=[0, 0, 0, 0], strides=[1, 1]](%2, %4), scope: TestMultipleInputs/ConvTranspose2d[deconv2d]
  %15 : Dynamic = onnx::Constant[value=<Tensor>](), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %16 : Dynamic = onnx::Constant[value=<Tensor>](), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %17 : Float(1, 53, 92, 92) = onnx::InstanceNormalization[epsilon=1e-05](%14, %15, %16), scope: TestMultipleInputs/InstanceNorm2d[in2d]
  %18 : Float(1, 53, 92, 92) = onnx::Add(%13, %17), scope: TestMultipleInputs
  return (%18);
}

[18 defined in (%18 : Float(1, 53, 92, 92) = onnx::Add(%13, %17), scope: TestMultipleInputs
)]
Graph outputs: ['18']
State dict: ['conv2d.weight', 'deconv2d.weight']
 ____
graph node: TestMultipleInputs/ConvTranspose2d[deconv2d]
type: onnx::ConvTranspose
inputs: ['input0']
outputs: ['TestMultipleInputs/ConvTranspose2d[deconv2d]']
name in state_dict: deconv2d
attrs: {'dilations': [1, 1], 'group': 1, 'kernel_shape': [1, 1], 'pads': [0, 0, 0, 0], 'strides': [1, 1]}
is_terminal: False
Converting transposed convolution ...
2018-10-20 00:17:50.934191: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
 ____
graph node: TestMultipleInputs/InstanceNorm2d[in2d]
type: onnx::Constant
inputs: []
outputs: ['TestMultipleInputs/InstanceNorm2d[in2d]']
name in state_dict: in2d
attrs: {'value': tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.])}
is_terminal: False
Converting constant ...
 ____
graph node: TestMultipleInputs/InstanceNorm2d[in2d]
type: onnx::Constant
inputs: []
outputs: ['TestMultipleInputs/InstanceNorm2d[in2d]']
name in state_dict: in2d
attrs: {'value': tensor([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.])}
is_terminal: False
Converting constant ...
 ____
graph node: TestMultipleInputs/InstanceNorm2d[in2d]
type: onnx::InstanceNormalization
inputs: ['5', '6', '7']
outputs: ['TestMultipleInputs/InstanceNorm2d[in2d]']
name in state_dict: in2d
attrs: {'epsilon': 1e-05}
is_terminal: False
Converting instancenorm ...
Traceback (most recent call last):
  File "multiple_layer_test.py", line 45, in <module>
    k_model = pytorch_to_keras(model, [input_var, input_var2, input_var3], [(inp, inp, inp,), (inp, inp, inp,), (inp, inp, inp,)], verbose=True)
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/pytorch2keras/converter.py", line 182, in pytorch_to_keras
    short_names
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/pytorch2keras/layers.py", line 626, in convert_instancenorm
    layers[scope_name] = lambda_layer(layers[inputs[0]])
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/keras/layers/core.py", line 682, in call
    return self.function(inputs, **arguments)
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/pytorch2keras/layers.py", line 622, in target_layer
    trainable=False)
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "~/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/normalization.py", line 120, in instance_norm
    inputs.name, params_shape))
ValueError: Inputs deconv2d0.27781545017061593/transpose_1:0 has undefined channels dimension (?,).
```

---
In my environment.
+ PyTorch 0.4.0
+ Keras 2.2.2
+ Tensorflow 1.9.0

**Comment by nerox8664** [comment]
Hello @UdonDa!
Thank you for the issue. I've found the [similar problem](https://github.com/keras-team/keras/issues/6777) and implemented simple solution to fix this bug. 
Please, pull the latest commit and try to convert your model again.

**Comment by UdonDa** [comment]
Hello @nerox8664!
Thanks for update! 
I can convert my model!!!!
