### ISSUE TITLE
couldn't install the tools

### ISSUE THREAD

**Issue by wangyunxiaa** [nerox8664/pytorch2keras#40]
when I do `pip install pytorch2keras`  in my virtual environment “conda，python3.6” I got an error:
`Collecting pytorch2keras
  Downloading https://files.pythonhosted.org/packages/2f/61/9fd96f62814ddf7d0a3d60db85be6965451c7d6efd8d5c52b1877db68bd3/pytorch2keras-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/yx.wang/anaconda3/envs/py3torch2keras/lib/python3.6/site-packages/pip/_internal/download.py", line 436, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zk3qnkav/pytorch2keras/setup.py", line 16, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-install-zk3qnkav/pytorch2keras/setup.py", line 16, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/home/yx.wang/anaconda3/envs/py3torch2keras/lib/python3.6/site-packages/pip/_internal/req/req_file.py", line 82, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/home/yx.wang/anaconda3/envs/py3torch2keras/lib/python3.6/site-packages/pip/_internal/download.py", line 440, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip._internal.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zk3qnkav/pytorch2keras/
`

**Comment by nerox8664** [comment]
Hello there. Yep, `requirements.txt` is missing in the previous package version. I fixed it in the latest pypi version.
